// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ratings.Infrastructure;

#nullable disable

namespace Ratings.Infrastructure.Migrations
{
    [DbContext(typeof(RatingContext))]
    [Migration("20230414060433_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.HasSequence("employerseq", "rating")
                .IncrementsBy(10);

            modelBuilder.HasSequence("paymentseq", "rating")
                .IncrementsBy(10);

            modelBuilder.Entity("Ratings.Domain.AggregatesModel.EmployerAggregate.Employer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "employerseq", "rating");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasColumnName("points");

                    b.Property<int>("_rankingId")
                        .HasColumnType("int")
                        .HasColumnName("ranking_id");

                    b.HasKey("Id");

                    b.HasIndex("_rankingId");

                    b.ToTable("employers", "rating");
                });

            modelBuilder.Entity("Ratings.Domain.AggregatesModel.EmployerAggregate.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "paymentseq", "rating");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int")
                        .HasColumnName("employer_id");

                    b.Property<DateTime>("_contributionMonth")
                        .HasColumnType("datetime2")
                        .HasColumnName("contribution_month");

                    b.Property<DateTime>("_dueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("due_date");

                    b.Property<decimal>("_paidAmount")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)")
                        .HasColumnName("paid_amount");

                    b.Property<DateTime>("_paymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("payment_date");

                    b.Property<bool>("_status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.ToTable("payments", "rating");
                });

            modelBuilder.Entity("Ratings.Domain.AggregatesModel.EmployerAggregate.Ranking", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("ranking", "rating");
                });

            modelBuilder.Entity("Ratings.Domain.AggregatesModel.EmployerAggregate.Employer", b =>
                {
                    b.HasOne("Ratings.Domain.AggregatesModel.EmployerAggregate.Ranking", "Ranking")
                        .WithMany()
                        .HasForeignKey("_rankingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ranking");
                });

            modelBuilder.Entity("Ratings.Domain.AggregatesModel.EmployerAggregate.Payment", b =>
                {
                    b.HasOne("Ratings.Domain.AggregatesModel.EmployerAggregate.Employer", null)
                        .WithMany("Payments")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ratings.Domain.AggregatesModel.EmployerAggregate.Employer", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
